/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false apps/server/src/worker-configuration.d.ts` (hash: 6027c62ac1c51f5afd028d379297bc52)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	PLUGIN_SUBMISSION_WORKFLOW: Workflow<Parameters<import("./runtime").PluginSubmissionWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./runtime");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
