/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false apps/server/src/worker-configuration.d.ts` (hash: 9c791ca59ac8911a6acea3babf97c9ba)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
